### PR TITLE
add cf and spectre flags

### PR DESCRIPTION
**Pull request by sbatten**

### CODE REVIEW

**Review by TylerLeonhardt — APPROVED** [review]
though I'd prefer if you didn't put it in a condition

**Comment by deepak1556** [comment]
https://github.com/microsoft/node-native-keymap/pull/39#issuecomment-1057038073 applies here as well, also yeah condition is not required to specify msvs_settings.

**Comment by deepak1556** [comment]
Should be rebased once https://github.com/microsoft/node-native-watchdog/pull/4 gets merged, for testing.

**Review by deepak1556 — APPROVED** [review]

**Comment by alexdima** [comment]
Continued at https://github.com/microsoft/vscode/pull/144670

**Pull request merged**
